[workspace]
members = [
    "crates/requests",
    "crates/requests-python",
]
resolver = "3"

[workspace.package]
version = "1.0.0-beta.1"
edition = "2024"
license = "Apache-2.0"
authors = ["Puneet Chandna"]
homepage = "https://github.com/puneet-chandna/requests-native"
repository = "https://github.com/puneet-chandna/requests-native"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
pyo3 = "0.29"

[profile.fuzz]
inherits = "release"
debug = true
codegen-units = 1
