[package]
name = "requests-python"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "_requests_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true, features = ["extension-module"] }
requests = { path = "../requests" }
tokio = { version = "1", features = ["sync", "time"] }

[lints]
workspace = true
